### PR TITLE
Add support for login captcha

### PR DESCRIPTION
**Pull request by Toilal**
When trying to connect too many times with wrong password, a captcha can be requested. This captcha is really simple and can be solved by the provider.

This implements the captcha resolution if requested at login time.

### CODE REVIEW

**Comment by Toilal** [comment]
Tested and working properly, after locking the account with wrong password.

**Comment by Toilal** [comment]
@djoole Did you have time to review and merge this one ? I'm using it, it works properly.

**Comment by djoole** [comment]
Sorry, I couldn't find time to test it yet.
Will try to do that soon and will merge it if everything is ok.
Thanks for improving the provider :)

**Comment by djoole** [comment]
No time to test it, merged it anyway :)

**Pull request merged**
